name: deploy frontend
on:
  push:
    branches:
      - deploy-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: habits

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'
      - name: cache nodejs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install deps
        run: npm ci
      - name: configure gh-pages auth
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "support+actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: deploy
        run: npm run deploy
        env:
          CI: false